name: Bump Formula CI

on:
  release:
    types: [released]

env:
  TAP_REPO_OWNER: ${{ github.repository_owner }}
  TAP_REPO_NAME: homebrew-public

jobs:
  examine-release:
    name: Examine the release
    runs-on: ubuntu-latest
    steps:
      - name: Exract release info
        id: release-info
        env:
          GH_TAG_REF: ${{ github.ref }}
        shell: python3 {0}
        run: |
          import os, re, sys

          # Extract tag name
          tag_ref = os.environ['GH_TAG_REF']
          tag_name = re.match(
            r"^(?:refs\/tags\/(?P<tag>.*))",
            tag_ref
          ).group("tag")

          print("tag of the release: {tag_name}".format(tag_name=tag_name))
          print("::set-output name=tag::{tag_name}".format(tag_name=tag_name))

          # NOTE: some repositories don't use SemVer scheme
          # Extracts version, excludes prerelease
          version_match = re.match(r"^v?(?P<version>\d[\d\.]*)", tag_name)

          if version_match:
            version = version_match.group("version")
            print("version: {version}".format(version=version))
            print("::set-output name=version::{version}".format(version=version))
          else:
            # FIXME: fix error message
            err_msg = "Release tag does not look like a version tag."
            print("::error file=PLACEHOLDER,line=1,col=1::{err_msg}".format(err_msg=err_msg))
            sys.exit(err_msg)

      - name: Checkout tap repo
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TAP_REPO_OWNER }}/${{ env.TAP_REPO_NAME }}
          path: tap_repo